In [1]:
import numpy as np
import pandas as pd

In [3]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [4]:
df= pd.read_csv('Titanic Train.csv')

In [5]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [6]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['Survived']),df['Survived'],
                                                 test_size=0.2)

In [8]:
X_train

PassengerId  Pclass                                              Name  \
100          101       3                           Petranec, Miss. Matilda   
650          651       3                                 Mitkoff, Mr. Mito   
831          832       2                   Richards, Master. George Sibley   
684          685       2                 Brown, Mr. Thomas William Solomon   
655          656       2                         Hickman, Mr. Leonard Mark   
..           ...     ...                                               ...   
23            24       1                      Sloper, Mr. William Thompson   
180          181       3                      Sage, Miss. Constance Gladys   
603          604       3                         Torber, Mr. Ernst William   
368          369       3                               Jermyn, Miss. Annie   
871          872       1  Beckwith, Mrs. Richard Leonard (Sallie Monypeny)   

        Sex    Age  SibSp  Parch        Ticket     Fare Cabin Embarked  
100  female  28.00      0      0        349245   7.8958   NaN        S  
650    male    NaN      0      0        349221   7.8958   NaN        S  
831    male   0.83      1      1         29106  18.7500   NaN        S  
684    male  60.00      1      1         29750  39.0000   NaN        S  
655    male  24.00      2      0  S.O.C. 14879  73.5000   NaN        S  
..      ...    ...    ...    ...           ...      ...   ...      ...  
23     male  28.00      0      0        113788  35.5000    A6        S  
180  female    NaN      8      2      CA. 2343  69.5500   NaN        S  
603    male  44.00      0      0        364511   8.0500   NaN        S  
368  female    NaN      0      0         14313   7.7500   NaN        Q  
871  female  47.00      1      1         11751  52.5542   D35        S  

[712 rows x 11 columns]

# without use of CT

In [10]:
#adding simple imputer to embarked column
si = SimpleImputer()
X_train_Embarked = si.fit_transform(X_train[['Embarked']])

#also the test data
X_test_Embarked = si.fit_transform(X_test[['Embarked']])

X_train_Embarked



ValueError: Cannot use mean strategy with non-numeric data:
could not convert string to float: 'S'

In [11]:
si = SimpleImputer()
X_train_Age = si.fit_transform(X_train[['Age']])

#also the test data
X_test_Age = si.fit_transform(X_test[['Age']])

X_train_Age

array([[28.        ],
       [29.78127367],
       [ 0.83      ],
       [60.        ],
       [24.        ],
       [29.        ],
       [28.        ],
       [ 3.        ],
       [26.        ],
       [54.        ],
       [ 5.        ],
       [32.        ],
       [29.78127367],
       [29.78127367],
       [24.        ],
       [ 8.        ],
       [ 6.        ],
       [52.        ],
       [19.        ],
       [18.        ],
       [19.        ],
       [30.        ],
       [40.        ],
       [52.        ],
       [24.        ],
       [41.        ],
       [36.        ],
       [29.        ],
       [20.        ],
       [17.        ],
       [25.        ],
       [29.78127367],
       [16.        ],
       [23.        ],
       [25.        ],
       [29.        ],
       [22.        ],
       [27.        ],
       [42.        ],
       [22.        ],
       [27.        ],
       [23.        ],
       [29.78127367],
       [19.        ],
       [19.        ],
       [32

In [12]:
## all the missing value of age is filled by the mean of the total age

In [13]:
## hence the missing data of categorical column can not be filled

In [21]:
df1= pd.read_csv('EG2 DATA.csv')

In [22]:
df1

age gender  fever cough city has_covid
0    60      M  123.0  MILD  KOL         N
1    45      M  102.0  MILD  MUM         Y
2    12      M   98.0  MILD  DEL         Y
3    48      F   78.0  HIGH  MUM         Y
4    78      F   79.0  HIGH  DEL         Y
5    79      F   75.0  MILD  KOL         N
6    42      F   74.0  HIGH  KOL         N
7    13      M   75.0  MILD  KOL         N
8    15      F  102.0  MILD  MUM         N
9    45      M  103.0  HIGH  MUM         N
10   64      F    NaN  HIGH  DEL         N
11   54      F    NaN  HIGH  DEL         Y
12   58      M    NaN  MILD  KOL         Y

In [23]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df1.drop(columns=['has_covid']),df1['has_covid'],
                                                 test_size=0.2)

In [33]:
X_train

age gender  fever cough city
3   48      F   78.0  HIGH  MUM
7   13      M   75.0  MILD  KOL
8   15      F  102.0  MILD  MUM
9   45      M  103.0  HIGH  MUM
2   12      M   98.0  MILD  DEL
1   45      M  102.0  MILD  MUM
4   78      F   79.0  HIGH  DEL
6   42      F   74.0  HIGH  KOL
0   60      M  123.0  MILD  KOL
5   79      F   75.0  MILD  KOL

In [27]:
df1['city'].value_counts()

city
KOL    5
MUM    4
DEL    4
Name: count, dtype: int64

In [30]:
df1.isnull().sum()

age          0
gender       0
fever        3
cough        0
city         0
has_covid    0
dtype: int64

In [35]:
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

#also the test data
X_test_fever = si.fit_transform(X_test[['fever']])

X_train_fever
X_test_fever

C:\Users\rahul\anaconda3\Lib\site-packages\sklearn\impute\_base.py:555: UserWarning: Skipping features without any observed values: ['fever']. At least one non-missing value is needed for imputation with strategy='mean'.
  warnings.warn(


array([], shape=(3, 0), dtype=float64)

In [34]:
X_test_fever

array([], shape=(3, 0), dtype=float64)

In [38]:
#ordinal encoding in cough column 
oe = OrdinalEncoder(categories=[['MILD','HIGH']])
X_train_cough= oe.fit_transform(X_train[['cough']])

X_test_cough= oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(10, 1)

In [39]:
X_train_cough

array([[1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.]])

In [40]:
# oHE in gender and city column
ohe = OneHotEncoder(drop= 'first',sparse_output= False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

#for test data
X_test_gender_city = ohe.fit_transform(X_train[['gender','city']])

X_train_gender_city

array([[0., 0., 1.],
       [1., 1., 0.],
       [0., 0., 1.],
       [1., 0., 1.],
       [1., 0., 0.],
       [1., 0., 1.],
       [0., 0., 0.],
       [0., 1., 0.],
       [1., 1., 0.],
       [0., 1., 0.]])

In [41]:
X_train_gender_city.shape

(10, 3)

In [42]:
## Extracting age
X_train_age= X_train.drop(columns=['gender','fever','cough','city']).values


X_test_age= X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape


(10, 1)

In [44]:
##now we merge all transform column
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
                        
    
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)
                        
    
X_train_transformed    

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 2 has size 10

# with CT

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [4]:
from sklearn.compose import ColumnTransformer

In [5]:
df1= pd.read_csv('EG2 DATA.csv')

In [6]:
df1

age gender  fever cough city has_covid
0    60      M  123.0  MILD  KOL         N
1    45      M  102.0  MILD  MUM         Y
2    12      M   98.0  MILD  DEL         Y
3    48      F   78.0  HIGH  MUM         Y
4    78      F   79.0  HIGH  DEL         Y
5    79      F   75.0  MILD  KOL         N
6    42      F   74.0  HIGH  KOL         N
7    13      M   75.0  MILD  KOL         N
8    15      F  102.0  MILD  MUM         N
9    45      M  103.0  HIGH  MUM         N
10   64      F    NaN  HIGH  DEL         N
11   54      F    NaN  HIGH  DEL         Y
12   58      M    NaN  MILD  KOL         Y

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df1.drop(columns=['has_covid']),df1['has_covid'],
                                                 test_size=0.2)

In [14]:
X_train

age gender  fever cough city
2    12      M   98.0  MILD  DEL
5    79      F   75.0  MILD  KOL
9    45      M  103.0  HIGH  MUM
0    60      M  123.0  MILD  KOL
6    42      F   74.0  HIGH  KOL
3    48      F   78.0  HIGH  MUM
8    15      F  102.0  MILD  MUM
1    45      M  102.0  MILD  MUM
10   64      F    NaN  HIGH  DEL
7    13      M   75.0  MILD  KOL

In [11]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
('tnf2',OrdinalEncoder(categories=[['MILD','HIGH']]),['cough']),
 ('tnf3',OneHotEncoder(sparse=False,drop='first'),['gender','city'])
] ,remainder= 'passthrough')

In [15]:
transformer.fit_transform(X_train)

C:\Users\rahul\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[ 98.        ,   0.        ,   1.        ,   0.        ,
          0.        ,  12.        ],
       [ 75.        ,   0.        ,   0.        ,   1.        ,
          0.        ,  79.        ],
       [103.        ,   1.        ,   1.        ,   0.        ,
          1.        ,  45.        ],
       [123.        ,   0.        ,   1.        ,   1.        ,
          0.        ,  60.        ],
       [ 74.        ,   1.        ,   0.        ,   1.        ,
          0.        ,  42.        ],
       [ 78.        ,   1.        ,   0.        ,   0.        ,
          1.        ,  48.        ],
       [102.        ,   0.        ,   0.        ,   0.        ,
          1.        ,  15.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          1.        ,  45.        ],
       [ 92.22222222,   1.        ,   0.        ,   0.        ,
          0.        ,  64.        ],
       [ 75.        ,   0.        ,   1.        ,   1.        ,
          0.        ,  13. 

In [16]:
transformer.fit_transform(X_train).shape

C:\Users\rahul\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


(10, 6)

In [17]:
transformer.transform(X_test)

array([[92.22222222,  0.        ,  1.        ,  1.        ,  0.        ,
        58.        ],
       [92.22222222,  1.        ,  0.        ,  0.        ,  0.        ,
        54.        ],
       [79.        ,  1.        ,  0.        ,  0.        ,  0.        ,
        78.        ]])

In [18]:
transformer.transform(X_test).shape

(3, 6)