In [1]:
import numpy as np
import pandas as pd

In [6]:
df = pd.read_csv('eg data.csv')

In [7]:
df.head()

gender review education purchased
0      f      g         u         y
1      f      g         p         n
2      f      g         u         n
3      f      a         p         n
4      m      a         p         n

In [8]:
## in review and edu we apply ordinal encoding as it has relation between category and in purchased(output)we apply label encoding 

In [36]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop('Purchased', axis=1),
                                                   df['Purchased'],
                                                   test_size=0.3,
                                                   random_state=0)
X_train.shape,X_test.shape

ValueError: No axis named 1 for object type Series

In [33]:
sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(df.drop('Purchased', axis=1),
                                                   df['Purchased'],
                                                   test_size=0.3,
                                                   random_state=0)
X_train.shape,X_test.shape

SyntaxError: invalid syntax (2663442371.py, line 1)

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('eg data.csv')

In [3]:
df.head()

gender review education purchased
0      f      g         u         y
1      f      g         p         n
2      f      g         u         n
3      f      a         p         n
4      m      a         p         n

In [4]:
df= df.iloc[:,1:]

In [5]:
df.head()

review education purchased
0      g         u         y
1      g         p         n
2      g         u         n
3      a         p         n
4      a         p         n

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)


In [7]:
X_train

review education
5       a         p
8       b         u
7       b         p
10      b         u
3       a         p
11      g         u
1       g         p
2       g         u
0       g         u

In [8]:
from sklearn.preprocessing import OrdinalEncoder

In [10]:
oe= OrdinalEncoder(categories= [['b','a','g'],['u','p']])

In [11]:
X_train= oe.transform(X_train)

AttributeError: 'OrdinalEncoder' object has no attribute '_missing_indices'

In [12]:
oe.fit(X_train)

OrdinalEncoder(categories=[['b', 'a', 'g'], ['u', 'p']])

In [16]:
X_train= oe.transform(X_train)
X_test= oe.transform(X_test)

C:\Users\rahul\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [14]:
X_train

array([[1., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [2., 0.],
       [2., 1.],
       [2., 0.],
       [2., 0.]])

In [17]:
X_test

review education
9      b         u
6      a         p
4      a         p

In [18]:
X_test= oe.transform(X_test)

In [19]:
X_test

array([[0., 0.],
       [1., 1.],
       [1., 1.]])

In [20]:
##we apply the ordinal encoding in the input(X) data and for output column(y) we apply label encoding

In [21]:
from sklearn.preprocessing import labelEncoder

ImportError: cannot import name 'labelEncoder' from 'sklearn.preprocessing' (C:\Users\rahul\anaconda3\Lib\site-packages\sklearn\preprocessing\__init__.py)

In [22]:
from sklearn.preprocessing import LabelEncoder

In [23]:
le= LabelEncoder()

In [24]:
le.fit(y_train)

LabelEncoder()

In [25]:
le.classes_

array(['n', 'y'], dtype=object)

In [26]:
y_train = le.transform(y_train)
y_test =  le.transform(y_test)                      

In [27]:
y_train

array([1, 1, 1, 0, 0, 0, 0, 0, 1])

In [28]:
y_test

array([1, 1, 0])